# Generated by Django 4.0.3 on 2023-01-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
